// Generated by kayak for the `copal` contract v0.1.0. Do not edit.

export interface File {
  id: string
  path: string
  state: string
  access: string
  contentType: string
  size?: number
  digest?: string
  metadata: unknown
  versionCount: number
  createdAt: string
  updatedAt: string
}

export interface FilePage {
  items: File[]
  next_cursor?: string | null
}

export interface FileVersion {
  id: string
  number: number
  contentType: string
  size: number
  digest: string
  metadataSnapshot: unknown
  createdBy?: string
  createdAt: string
}

export interface FileVersionPage {
  items: FileVersion[]
  next_cursor?: string | null
}

export interface Webhook {
  id: string
  targetUrl: string
  events: string
  active: boolean
  createdAt: string
}

export interface WebhookPage {
  items: Webhook[]
  next_cursor?: string | null
}

export interface WebhookDelivery {
  id: string
  state: string
  attempts: number
  lastStatus?: number
  nextAttemptAt?: string
  createdAt: string
}

export interface WebhookDeliveryPage {
  items: WebhookDelivery[]
  next_cursor?: string | null
}

export interface Event {
  id: string
  action: string
  payload: unknown
  createdAt: string
}

export interface EventPage {
  items: Event[]
  next_cursor?: string | null
}

export interface Run {
  id: string
  workflow: string
  status: string
  output?: unknown
  error?: string
  createdAt: string
  endedAt?: string
}

export interface RunPage {
  items: Run[]
  next_cursor?: string | null
}

export class Client {
  constructor(private baseUrl: string, private tenant: string) {}

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method,
      headers: {
        'x-copal-tenant': this.tenant,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    if (!response.ok) throw new Error(`${method} ${path}: ${response.status}`)
    if (response.status === 204) return undefined as T
    return (await response.json()) as T
  }

  listFiles(limit?: number, cursor?: string): Promise<FilePage> {
    const query = new URLSearchParams()
    if (limit !== undefined) query.set('limit', String(limit))
    if (cursor !== undefined) query.set('cursor', cursor)
    const suffix = query.size > 0 ? `?${query}` : ''
    return this.request('GET', `/v1/files${suffix}`)
  }

  getFile(id: string): Promise<File> {
    return this.request('GET', `/v1/files/${id}`)
  }

  listVersionsFiles(id: string, limit?: number, cursor?: string): Promise<FileVersionPage> {
    const query = new URLSearchParams()
                     if (limit !== undefined) query.set('limit', String(limit))
                     if (cursor !== undefined) query.set('cursor', cursor)
                     const suffix = query.size > 0 ? `?${query}` : ''
                     return this.request('GET', `/v1/files/${id}/versions${suffix}`)
  }

  createFile(input: Record<string, unknown>): Promise<File> {
    return this.request('POST', `/v1/files`, input)
  }

  issueUrlFile(id: string, input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/${id}/url`, input)
  }

  issueUploadUrlFile(id: string, input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/${id}/upload-url`, input)
  }

  issueEdgeUrlFile(id: string, input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/${id}/edge-url`, input)
  }

  requestRenditionFile(id: string, input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/${id}/renditions`, input)
  }

  transformFile(id: string, input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/${id}/transform`, input)
  }

  fetchFile(input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/files/fetch`, input)
  }

  removeFile(id: string): Promise<void> {
    return this.request('DELETE', `/v1/files/${id}`)
  }

  listWebhooks(limit?: number, cursor?: string): Promise<WebhookPage> {
    const query = new URLSearchParams()
    if (limit !== undefined) query.set('limit', String(limit))
    if (cursor !== undefined) query.set('cursor', cursor)
    const suffix = query.size > 0 ? `?${query}` : ''
    return this.request('GET', `/v1/webhooks${suffix}`)
  }

  getWebhook(id: string): Promise<Webhook> {
    return this.request('GET', `/v1/webhooks/${id}`)
  }

  listDeliveriesWebhooks(id: string, limit?: number, cursor?: string): Promise<WebhookDeliveryPage> {
    const query = new URLSearchParams()
                     if (limit !== undefined) query.set('limit', String(limit))
                     if (cursor !== undefined) query.set('cursor', cursor)
                     const suffix = query.size > 0 ? `?${query}` : ''
                     return this.request('GET', `/v1/webhooks/${id}/deliveries${suffix}`)
  }

  registerWebhook(input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/webhooks`, input)
  }

  removeWebhook(id: string): Promise<void> {
    return this.request('DELETE', `/v1/webhooks/${id}`)
  }

  listEvents(limit?: number, cursor?: string): Promise<EventPage> {
    const query = new URLSearchParams()
    if (limit !== undefined) query.set('limit', String(limit))
    if (cursor !== undefined) query.set('cursor', cursor)
    const suffix = query.size > 0 ? `?${query}` : ''
    return this.request('GET', `/v1/events${suffix}`)
  }

  getEvent(id: string): Promise<Event> {
    return this.request('GET', `/v1/events/${id}`)
  }

  listRuns(limit?: number, cursor?: string): Promise<RunPage> {
    const query = new URLSearchParams()
    if (limit !== undefined) query.set('limit', String(limit))
    if (cursor !== undefined) query.set('cursor', cursor)
    const suffix = query.size > 0 ? `?${query}` : ''
    return this.request('GET', `/v1/runs${suffix}`)
  }

  getRun(id: string): Promise<Run> {
    return this.request('GET', `/v1/runs/${id}`)
  }

  startRun(input: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/runs`, input)
  }

  retryRun(id: string): Promise<Record<string, unknown>> {
    return this.request('POST', `/v1/runs/${id}/retry`)
  }

  search(q: string, mode?: string, limit?: number, prefix?: string, contentType?: string, cursor?: string, facets?: string): Promise<unknown> {
    const query = new URLSearchParams()
    query.set('q', String(q))
    if (mode !== undefined) query.set('mode', String(mode))
    if (limit !== undefined) query.set('limit', String(limit))
    if (prefix !== undefined) query.set('prefix', String(prefix))
    if (contentType !== undefined) query.set('content_type', String(contentType))
    if (cursor !== undefined) query.set('cursor', String(cursor))
    if (facets !== undefined) query.set('facets', String(facets))
    const suffix = query.size > 0 ? `?${query}` : ''
    return this.request('GET', `/v1/search${suffix}`)
  }

  fileText(id: string): Promise<unknown> {
    return this.request('GET', `/v1/files/${id}/text`)
  }

}
