"""Generated by janus for the `copal` contract v0.1.0. Do not edit."""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from typing import Any

@dataclass
class File:
  id: str
  path: str
  state: str
  access: str
  content_type: str
  metadata: Any
  version_count: int
  created_at: str
  updated_at: str
  size: int | None = None
  digest: str | None = None

@dataclass
class FilePage:
  items: list[File] = field(default_factory=list)
  next_cursor: str | None = None

@dataclass
class Webhook:
  id: str
  target_url: str
  events: str
  active: bool
  created_at: str

@dataclass
class WebhookPage:
  items: list[Webhook] = field(default_factory=list)
  next_cursor: str | None = None

@dataclass
class Event:
  id: str
  action: str
  payload: Any
  created_at: str

@dataclass
class EventPage:
  items: list[Event] = field(default_factory=list)
  next_cursor: str | None = None

@dataclass
class Run:
  id: str
  workflow: str
  status: str
  created_at: str
  output: Any | None = None
  error: str | None = None
  ended_at: str | None = None

@dataclass
class RunPage:
  items: list[Run] = field(default_factory=list)
  next_cursor: str | None = None

class Client:
  def __init__(self, base_url: str, tenant: str) -> None:
    self.base_url = base_url.rstrip('/')
    self.tenant = tenant

  def _request(self, method: str, path: str, body: dict[str, Any] | None = None) -> Any:
    data = None if body is None else json.dumps(body).encode()
    headers = {'x-copal-tenant': self.tenant}
    if data is not None:
      headers['content-type'] = 'application/json'
    request = urllib.request.Request(
      f'{self.base_url}{path}', data=data, headers=headers, method=method,
    )
    with urllib.request.urlopen(request) as response:
      if response.status == 204:
        return None
      return json.loads(response.read())

  def list_files(self, limit: int | None = None, cursor: str | None = None) -> FilePage:
    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}
    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''
    payload = self._request('GET', f'/v1/files{suffix}')
    return FilePage(
      items=[File(**{k: v for k, v in item.items() if k in File.__dataclass_fields__}) for item in payload.get('items', [])],
      next_cursor=payload.get('next_cursor'),
    )

  def get_file(self, id: str) -> File:
    item = self._request('GET', f'/v1/files/{id}')
    return File(**{k: v for k, v in item.items() if k in File.__dataclass_fields__})

  def issue_url_file(self, id: str, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/files/{id}/url', body or {})

  def issue_upload_url_file(self, id: str, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/files/{id}/upload-url', body or {})

  def issue_edge_url_file(self, id: str, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/files/{id}/edge-url', body or {})

  def request_rendition_file(self, id: str, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/files/{id}/renditions', body or {})

  def remove_file(self, id: str) -> None:
    return self._request('DELETE', f'/v1/files/{id}')

  def list_webhooks(self, limit: int | None = None, cursor: str | None = None) -> WebhookPage:
    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}
    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''
    payload = self._request('GET', f'/v1/webhooks{suffix}')
    return WebhookPage(
      items=[Webhook(**{k: v for k, v in item.items() if k in Webhook.__dataclass_fields__}) for item in payload.get('items', [])],
      next_cursor=payload.get('next_cursor'),
    )

  def get_webhook(self, id: str) -> Webhook:
    item = self._request('GET', f'/v1/webhooks/{id}')
    return Webhook(**{k: v for k, v in item.items() if k in Webhook.__dataclass_fields__})

  def register_webhook(self, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/webhooks', body or {})

  def remove_webhook(self, id: str) -> None:
    return self._request('DELETE', f'/v1/webhooks/{id}')

  def list_events(self, limit: int | None = None, cursor: str | None = None) -> EventPage:
    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}
    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''
    payload = self._request('GET', f'/v1/events{suffix}')
    return EventPage(
      items=[Event(**{k: v for k, v in item.items() if k in Event.__dataclass_fields__}) for item in payload.get('items', [])],
      next_cursor=payload.get('next_cursor'),
    )

  def get_event(self, id: str) -> Event:
    item = self._request('GET', f'/v1/events/{id}')
    return Event(**{k: v for k, v in item.items() if k in Event.__dataclass_fields__})

  def list_runs(self, limit: int | None = None, cursor: str | None = None) -> RunPage:
    query = {k: v for k, v in {'limit': limit, 'cursor': cursor}.items() if v is not None}
    suffix = f'?{urllib.parse.urlencode(query)}' if query else ''
    payload = self._request('GET', f'/v1/runs{suffix}')
    return RunPage(
      items=[Run(**{k: v for k, v in item.items() if k in Run.__dataclass_fields__}) for item in payload.get('items', [])],
      next_cursor=payload.get('next_cursor'),
    )

  def get_run(self, id: str) -> Run:
    item = self._request('GET', f'/v1/runs/{id}')
    return Run(**{k: v for k, v in item.items() if k in Run.__dataclass_fields__})

  def start_run(self, body: dict[str, Any] | None = None) -> Any:
    return self._request('POST', f'/v1/runs', body or {})

  def retry_run(self, id: str) -> Any:
    return self._request('POST', f'/v1/runs/{id}/retry')

