// Code generated by janus for the `copal` contract v0.1.0; DO NOT EDIT.

package copal

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
)

type File struct {
	ID string `json:"id"`
	Path string `json:"path"`
	State string `json:"state"`
	Access string `json:"access"`
	ContentType string `json:"content_type"`
	Size *int64 `json:"size"`
	Digest *string `json:"digest"`
	Metadata any `json:"metadata"`
	VersionCount int64 `json:"version_count"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type FilePage struct {
	Items []File `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type FileVersion struct {
	ID string `json:"id"`
	Number int64 `json:"number"`
	ContentType string `json:"content_type"`
	Size int64 `json:"size"`
	Digest string `json:"digest"`
	MetadataSnapshot any `json:"metadata_snapshot"`
	CreatedBy string `json:"created_by"`
	CreatedAt string `json:"created_at"`
}

type FileVersionPage struct {
	Items []FileVersion `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type Webhook struct {
	ID string `json:"id"`
	TargetUrl string `json:"target_url"`
	Events string `json:"events"`
	Active bool `json:"active"`
	CreatedAt string `json:"created_at"`
}

type WebhookPage struct {
	Items []Webhook `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type WebhookDelivery struct {
	ID string `json:"id"`
	State string `json:"state"`
	Attempts int64 `json:"attempts"`
	LastStatus *int64 `json:"last_status"`
	NextAttemptAt *string `json:"next_attempt_at"`
	CreatedAt string `json:"created_at"`
}

type WebhookDeliveryPage struct {
	Items []WebhookDelivery `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type Event struct {
	ID string `json:"id"`
	Action string `json:"action"`
	Payload any `json:"payload"`
	CreatedAt string `json:"created_at"`
}

type EventPage struct {
	Items []Event `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type Run struct {
	ID string `json:"id"`
	Workflow string `json:"workflow"`
	Status string `json:"status"`
	Output any `json:"output"`
	Error *string `json:"error"`
	CreatedAt string `json:"created_at"`
	EndedAt *string `json:"ended_at"`
}

type RunPage struct {
	Items []Run `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

type Client struct {
	BaseURL string
	Tenant  string
	HTTP    *http.Client
}

func NewClient(baseURL, tenant string) *Client {
	return &Client{BaseURL: baseURL, Tenant: tenant, HTTP: http.DefaultClient}
}

func (c *Client) request(method, path string, body any, out any) error {
	var payload *bytes.Buffer
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		payload = bytes.NewBuffer(encoded)
	} else {
		payload = bytes.NewBuffer(nil)
	}
	request, err := http.NewRequest(method, c.BaseURL+path, payload)
	if err != nil {
		return err
	}
	request.Header.Set("x-copal-tenant", c.Tenant)
	if body != nil {
		request.Header.Set("content-type", "application/json")
	}
	response, err := c.HTTP.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode >= 400 {
		return fmt.Errorf("%s %s: %d", method, path, response.StatusCode)
	}
	if out == nil || response.StatusCode == 204 {
		return nil
	}
	return json.NewDecoder(response.Body).Decode(out)
}

func (c *Client) ListFiles(limit int, cursor string) (*FilePage, error) {
	query := url.Values{}
	if limit > 0 {
		query.Set("limit", fmt.Sprint(limit))
	}
	if cursor != "" {
		query.Set("cursor", cursor)
	}
	path := "/v1/files"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var page FilePage
	if err := c.request("GET", path, nil, &page); err != nil {
		return nil, err
	}
	return &page, nil
}

func (c *Client) GetFile(id string) (*File, error) {
	var out File
	if err := c.request("GET", "/v1/files/"+id, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) ListVersionsFiles(id string, limit int, cursor string) (*FileVersionPage, error) {
	query := url.Values{}
                 	if limit > 0 {
                 		query.Set("limit", fmt.Sprint(limit))
                 	}
                 	if cursor != "" {
                 		query.Set("cursor", cursor)
                 	}
                 	path := "/v1/files/" + id + "/versions"
                 	if encoded := query.Encode(); encoded != "" {
                 		path += "?" + encoded
                 	}
                 	var page FileVersionPage
                 	if err := c.request("GET", path, nil, &page); err != nil {
                 		return nil, err
                 	}
                 	return &page, nil
}

func (c *Client) IssueUrlFile(id string, input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/files" + "/" + id + "/url", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) IssueUploadUrlFile(id string, input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/files" + "/" + id + "/upload-url", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) IssueEdgeUrlFile(id string, input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/files" + "/" + id + "/edge-url", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RequestRenditionFile(id string, input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/files" + "/" + id + "/renditions", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RemoveFile(id string) error {
	return c.request("DELETE", "/v1/files" + "/" + id, nil, nil)
}

func (c *Client) ListWebhooks(limit int, cursor string) (*WebhookPage, error) {
	query := url.Values{}
	if limit > 0 {
		query.Set("limit", fmt.Sprint(limit))
	}
	if cursor != "" {
		query.Set("cursor", cursor)
	}
	path := "/v1/webhooks"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var page WebhookPage
	if err := c.request("GET", path, nil, &page); err != nil {
		return nil, err
	}
	return &page, nil
}

func (c *Client) GetWebhook(id string) (*Webhook, error) {
	var out Webhook
	if err := c.request("GET", "/v1/webhooks/"+id, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) ListDeliveriesWebhooks(id string, limit int, cursor string) (*WebhookDeliveryPage, error) {
	query := url.Values{}
                 	if limit > 0 {
                 		query.Set("limit", fmt.Sprint(limit))
                 	}
                 	if cursor != "" {
                 		query.Set("cursor", cursor)
                 	}
                 	path := "/v1/webhooks/" + id + "/deliveries"
                 	if encoded := query.Encode(); encoded != "" {
                 		path += "?" + encoded
                 	}
                 	var page WebhookDeliveryPage
                 	if err := c.request("GET", path, nil, &page); err != nil {
                 		return nil, err
                 	}
                 	return &page, nil
}

func (c *Client) RegisterWebhook(input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/webhooks", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RemoveWebhook(id string) error {
	return c.request("DELETE", "/v1/webhooks" + "/" + id, nil, nil)
}

func (c *Client) ListEvents(limit int, cursor string) (*EventPage, error) {
	query := url.Values{}
	if limit > 0 {
		query.Set("limit", fmt.Sprint(limit))
	}
	if cursor != "" {
		query.Set("cursor", cursor)
	}
	path := "/v1/events"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var page EventPage
	if err := c.request("GET", path, nil, &page); err != nil {
		return nil, err
	}
	return &page, nil
}

func (c *Client) GetEvent(id string) (*Event, error) {
	var out Event
	if err := c.request("GET", "/v1/events/"+id, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) ListRuns(limit int, cursor string) (*RunPage, error) {
	query := url.Values{}
	if limit > 0 {
		query.Set("limit", fmt.Sprint(limit))
	}
	if cursor != "" {
		query.Set("cursor", cursor)
	}
	path := "/v1/runs"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var page RunPage
	if err := c.request("GET", path, nil, &page); err != nil {
		return nil, err
	}
	return &page, nil
}

func (c *Client) GetRun(id string) (*Run, error) {
	var out Run
	if err := c.request("GET", "/v1/runs/"+id, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) StartRun(input map[string]any) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/runs", input, &out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RetryRun(id string) (map[string]any, error) {
	out := map[string]any{}
	if err := c.request("POST", "/v1/runs" + "/" + id + "/retry", nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

