//! Generated by janus for the `copal` contract v0.1.0. Do not edit.
//!
//! Dependencies: reqwest = { features = ["json"] }, serde =
//! { features = ["derive"] }, serde_json.

use serde::Deserialize;
use serde_json::Value;

#[derive(Debug, Clone, Deserialize)]
pub struct File {
    pub id: String,
    pub path: String,
    pub state: String,
    pub access: String,
    pub content_type: String,
    #[serde(default)]
    pub size: Option<i64>,
    #[serde(default)]
    pub digest: Option<String>,
    pub metadata: Value,
    pub version_count: i64,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FilePage {
    pub items: Vec<File>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FileVersion {
    pub id: String,
    pub number: i64,
    pub content_type: String,
    pub size: i64,
    pub digest: String,
    pub metadata_snapshot: Value,
    #[serde(default)]
    pub created_by: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FileVersionPage {
    pub items: Vec<FileVersion>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Webhook {
    pub id: String,
    pub target_url: String,
    pub events: String,
    pub active: bool,
    pub created_at: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct WebhookPage {
    pub items: Vec<Webhook>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct WebhookDelivery {
    pub id: String,
    pub state: String,
    pub attempts: i64,
    #[serde(default)]
    pub last_status: Option<i64>,
    #[serde(default)]
    pub next_attempt_at: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct WebhookDeliveryPage {
    pub items: Vec<WebhookDelivery>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Event {
    pub id: String,
    pub action: String,
    pub payload: Value,
    pub created_at: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct EventPage {
    pub items: Vec<Event>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Run {
    pub id: String,
    pub workflow: String,
    pub status: String,
    #[serde(default)]
    pub output: Option<Value>,
    #[serde(default)]
    pub error: Option<String>,
    pub created_at: String,
    #[serde(default)]
    pub ended_at: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct RunPage {
    pub items: Vec<Run>,
    #[serde(default)]
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Client {
    base_url: String,
    tenant: String,
    http: reqwest::Client,
}

pub type Error = Box<dyn std::error::Error + Send + Sync>;

impl Client {
    pub fn new(base_url: impl Into<String>, tenant: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            tenant: tenant.into(),
            http: reqwest::Client::new(),
        }
    }

    pub async fn list_files(&self, limit: Option<u32>, cursor: Option<&str>) -> Result<FilePage, Error> {
        let mut url = format!("{}/v1/files", self.base_url);
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(limit) = limit { query.push(("limit".into(), limit.to_string())); }
        if let Some(cursor) = cursor { query.push(("cursor".into(), cursor.to_string())); }
        if !query.is_empty() {
            let joined: Vec<String> = query.iter().map(|(k, v)| format!("{k}={v}")).collect();
            url = format!("{url}?{}", joined.join("&"));
        }
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn get_file(&self, id: &str) -> Result<File, Error> {
        let url = format!("{}/v1/files/{id}", self.base_url);
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn list_versions_files(&self, id: &str, limit: Option<u32>, cursor: Option<&str>)                  -> Result<FileVersionPage, Error> {
        let mut url = format!("{}/v1/files/{id}/versions", self.base_url);
        let mut query: Vec<(String, String)> = Vec::new();
                         if let Some(limit) = limit { query.push(("limit".into(), limit.to_string())); }
                         if let Some(cursor) = cursor { query.push(("cursor".into(), cursor.to_string())); }
                         if !query.is_empty() {
                             let joined: Vec<String> = query.iter().map(|(k, v)| format!("{k}={v}")).collect();
                             url = format!("{url}?{}", joined.join("&"));
                         }
                         Ok(self.http.get(url).header("x-copal-tenant", &self.tenant)                 .send().await?.error_for_status()?.json().await?)
    }

    pub async fn create_file(&self, input: Value) -> Result<File, Error> {
        let url = format!("{}/v1/files", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn issue_url_file(&self, id: &str, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/url", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn issue_upload_url_file(&self, id: &str, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/upload-url", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn issue_edge_url_file(&self, id: &str, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/edge-url", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn request_rendition_file(&self, id: &str, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/renditions", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn transform_file(&self, id: &str, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/transform", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn fetch_file(&self, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/files/fetch", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn remove_file(&self, id: &str) -> Result<(), Error> {
        let url = format!("{}/v1/files/{id}", self.base_url);
        self.http.delete(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?;
        Ok(())
    }

    pub async fn list_webhooks(&self, limit: Option<u32>, cursor: Option<&str>) -> Result<WebhookPage, Error> {
        let mut url = format!("{}/v1/webhooks", self.base_url);
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(limit) = limit { query.push(("limit".into(), limit.to_string())); }
        if let Some(cursor) = cursor { query.push(("cursor".into(), cursor.to_string())); }
        if !query.is_empty() {
            let joined: Vec<String> = query.iter().map(|(k, v)| format!("{k}={v}")).collect();
            url = format!("{url}?{}", joined.join("&"));
        }
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn get_webhook(&self, id: &str) -> Result<Webhook, Error> {
        let url = format!("{}/v1/webhooks/{id}", self.base_url);
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn list_deliveries_webhooks(&self, id: &str, limit: Option<u32>, cursor: Option<&str>)                  -> Result<WebhookDeliveryPage, Error> {
        let mut url = format!("{}/v1/webhooks/{id}/deliveries", self.base_url);
        let mut query: Vec<(String, String)> = Vec::new();
                         if let Some(limit) = limit { query.push(("limit".into(), limit.to_string())); }
                         if let Some(cursor) = cursor { query.push(("cursor".into(), cursor.to_string())); }
                         if !query.is_empty() {
                             let joined: Vec<String> = query.iter().map(|(k, v)| format!("{k}={v}")).collect();
                             url = format!("{url}?{}", joined.join("&"));
                         }
                         Ok(self.http.get(url).header("x-copal-tenant", &self.tenant)                 .send().await?.error_for_status()?.json().await?)
    }

    pub async fn register_webhook(&self, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/webhooks", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn remove_webhook(&self, id: &str) -> Result<(), Error> {
        let url = format!("{}/v1/webhooks/{id}", self.base_url);
        self.http.delete(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?;
        Ok(())
    }

    pub async fn list_events(&self, limit: Option<u32>, cursor: Option<&str>) -> Result<EventPage, Error> {
        let mut url = format!("{}/v1/events", self.base_url);
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(limit) = limit { query.push(("limit".into(), limit.to_string())); }
        if let Some(cursor) = cursor { query.push(("cursor".into(), cursor.to_string())); }
        if !query.is_empty() {
            let joined: Vec<String> = query.iter().map(|(k, v)| format!("{k}={v}")).collect();
            url = format!("{url}?{}", joined.join("&"));
        }
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn get_event(&self, id: &str) -> Result<Event, Error> {
        let url = format!("{}/v1/events/{id}", self.base_url);
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn list_runs(&self, limit: Option<u32>, cursor: Option<&str>) -> Result<RunPage, Error> {
        let mut url = format!("{}/v1/runs", self.base_url);
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(limit) = limit { query.push(("limit".into(), limit.to_string())); }
        if let Some(cursor) = cursor { query.push(("cursor".into(), cursor.to_string())); }
        if !query.is_empty() {
            let joined: Vec<String> = query.iter().map(|(k, v)| format!("{k}={v}")).collect();
            url = format!("{url}?{}", joined.join("&"));
        }
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn get_run(&self, id: &str) -> Result<Run, Error> {
        let url = format!("{}/v1/runs/{id}", self.base_url);
        Ok(self.http.get(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn start_run(&self, input: Value) -> Result<Value, Error> {
        let url = format!("{}/v1/runs", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).json(&input).send().await?.error_for_status()?.json().await?)
    }

    pub async fn retry_run(&self, id: &str) -> Result<Value, Error> {
        let url = format!("{}/v1/runs/{id}/retry", self.base_url);
        Ok(self.http.post(url).header("x-copal-tenant", &self.tenant).send().await?.error_for_status()?.json().await?)
    }

    pub async fn search(&self, q: &str, mode: Option<&str>, limit: Option<i64>, prefix: Option<&str>, content_type: Option<&str>, cursor: Option<&str>, facets: Option<&str>) -> Result<Value, Error> {
        let url = format!("{}/v1/search", self.base_url);
        let mut request = self.http.get(url)
            .header("x-copal-tenant", &self.tenant);
        request = request.query(&[("q", q)]);
        if let Some(value) = mode {
            request = request.query(&[("mode", value)]);
        }
        if let Some(value) = limit {
            request = request.query(&[("limit", value)]);
        }
        if let Some(value) = prefix {
            request = request.query(&[("prefix", value)]);
        }
        if let Some(value) = content_type {
            request = request.query(&[("content_type", value)]);
        }
        if let Some(value) = cursor {
            request = request.query(&[("cursor", value)]);
        }
        if let Some(value) = facets {
            request = request.query(&[("facets", value)]);
        }
        Ok(request.send().await?.error_for_status()?.json().await?)
    }

    pub async fn file_text(&self, id: &str) -> Result<Value, Error> {
        let url = format!("{}/v1/files/{id}/text", self.base_url);
        let request = self.http.get(url)
            .header("x-copal-tenant", &self.tenant);
        Ok(request.send().await?.error_for_status()?.json().await?)
    }

}
